export const themes = {
  discipline: {
    name: 'Discipline',
    primary: '#3B82F6',
    primaryHover: '#2563EB',
    secondary: '#1E40AF',
    accent: '#60A5FA',
    background: '#F8FAFC',
    surface: '#FFFFFF',
    card: '#FFFFFF',
    border: '#E2E8F0',
    text: '#1E293B',
    textSecondary: '#64748B',
    muted: '#F1F5F9',
    success: '#10B981',
    warning: '#F59E0B',
    error: '#EF4444',
    info: '#06B6D4',
    gradient: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    chartColors: ['#3B82F6', '#60A5FA', '#93C5FD', '#DBEAFE', '#EFF6FF'],
  },
  struggle: {
    name: 'Struggle',
    primary: '#EF4444',
    primaryHover: '#DC2626',
    secondary: '#B91C1C',
    accent: '#F87171',
    background: '#FEF2F2',
    surface: '#FFFFFF',
    card: '#FFFFFF',
    border: '#FCA5A5',
    text: '#7F1D1D',
    textSecondary: '#991B1B',
    muted: '#FEE2E2',
    success: '#10B981',
    warning: '#F59E0B',
    error: '#DC2626',
    info: '#06B6D4',
    gradient: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
    chartColors: ['#EF4444', '#F87171', '#FCA5A5', '#FECACA', '#FEE2E2'],
  },
  performance: {
    name: 'Performance',
    primary: '#10B981',
    primaryHover: '#059669',
    secondary: '#047857',
    accent: '#34D399',
    background: '#F0FDF4',
    surface: '#FFFFFF',
    card: '#FFFFFF',
    border: '#BBF7D0',
    text: '#064E3B',
    textSecondary: '#047857',
    muted: '#D1FAE5',
    success: '#059669',
    warning: '#F59E0B',
    error: '#EF4444',
    info: '#06B6D4',
    gradient: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    chartColors: ['#10B981', '#34D399', '#6EE7B7', '#A7F3D0', '#D1FAE5'],
  },
  warrior: {
    name: 'Warrior',
    primary: '#8B5CF6',
    primaryHover: '#7C3AED',
    secondary: '#6D28D9',
    accent: '#A78BFA',
    background: '#FAF5FF',
    surface: '#FFFFFF',
    card: '#FFFFFF',
    border: '#DDD6FE',
    text: '#4C1D95',
    textSecondary: '#6D28D9',
    muted: '#EDE9FE',
    success: '#10B981',
    warning: '#F59E0B',
    error: '#EF4444',
    info: '#06B6D4',
    gradient: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    chartColors: ['#8B5CF6', '#A78BFA', '#C4B5FD', '#DDD6FE', '#EDE9FE'],
  },
} as const

export type ThemeType = keyof typeof themes

export function getThemeColors(theme: ThemeType) {
  return themes[theme]
}

export function getCSSVariables(theme: ThemeType) {
  const colors = themes[theme]
  return {
    '--primary': colors.primary,
    '--primary-hover': colors.primaryHover,
    '--secondary': colors.secondary,
    '--accent': colors.accent,
    '--background': colors.background,
    '--surface': colors.surface,
    '--card': colors.card,
    '--border': colors.border,
    '--text': colors.text,
    '--text-secondary': colors.textSecondary,
    '--muted': colors.muted,
    '--success': colors.success,
    '--warning': colors.warning,
    '--error': colors.error,
    '--info': colors.info,
    '--gradient': colors.gradient,
  }
}
